Added template project
TouchInstinct/android-project-template pull request #1
Opened 2019-05-14 14:24 UTC by RationalEgoism

2019-05-17 09:13 UTC, maxbach requested changes

2019-05-17 09:13 UTC, maxbach commented on app/.gitignore
> +/build
Два гитигнора?

2019-05-17 09:13 UTC, maxbach commented on app/build.gradle
> +        customerProd {
customer один, а должно быть четыре

2019-05-17 09:13 UTC, maxbach commented on app/build.gradle
> +            buildConfigField "String", "API_URL", '"https://api.cifra.pw/api/"'
Замени на что-то нейтральное

2019-05-17 09:13 UTC, maxbach commented on app/build.gradle
> +    implementation 'com.squareup.okhttp3:logging-interceptor:3.14.1'
Засунь в переменные

2019-05-17 09:13 UTC, maxbach commented on app/build.gradle
> +    //noinspection GradleDependency NewerVersionAvailable
Убери все noInspection, они теперь не нужны

2019-05-17 09:13 UTC, maxbach commented on app/src/main/AndroidManifest.xml
> +        android:label="VTBAccountingApplication"
Замени все на нейтральное

2019-05-17 09:13 UTC, maxbach commented on app/src/main/java/ru/touchin/template/TemplateApplication.kt
> +    override fun onCreate() {
Добавь код для инициализации фабрика, с TODO: Delete after fabric init

2019-05-17 09:13 UTC, maxbach commented on app/src/main/java/ru/touchin/template/viewmodel/StartupViewModel.kt
> +class StartupViewModel @Inject constructor() : RxViewModel() {
Убери скобки

2019-05-17 09:13 UTC, maxbach commented on app/src/main/res/layout/common_activity.xml
> +        android:orientation="vertical"/>
orientation лищний

2019-05-17 09:14 UTC, maxbach commented on app/.gitignore
> +/build
Еще не хватает release-notes.txt, кажется

2019-05-17 09:17 UTC, maxbach commented on app/.gitignore
> +/build
А .gitmodules есть?

2019-05-21 13:38 UTC, RationalEgoism commented on app/build.gradle
> +        customerProd {
https://github.com/TouchInstinct/Styleguide/blob/master/general/setupBuildGuide.md

2019-05-21 14:30 UTC, RationalEgoism commented on app/src/main/java/ru/touchin/template/TemplateApplication.kt
> +    override fun onCreate() {
Это есть в классе TouchinApp:68
https://fabric.io/kits/android/crashlytics/install

2019-05-21 14:35 UTC, RationalEgoism commented on app/.gitignore
> +/build
> А .gitmodules есть?

Файл появляется после подключения сабмодулей, которое описано в стайл-гайдах

2019-05-24 16:08 UTC, maxbach approved these changes

2019-05-24 16:31 UTC, saifer2505 commented on app/src/main/AndroidManifest.xml
> +        android:roundIcon="@mipmap/ic_launcher"
`android:roundIcon="@mipmap/ic_launcher_round"`

2019-05-24 16:31 UTC, saifer2505 commented on app/src/main/AndroidManifest.xml
> +        android:label="TemplateApplication"
android:label="@string/common_global_app_name"

2019-05-24 16:31 UTC, saifer2505 commented on app/src/main/AndroidManifest.xml
> +            android:name="ru.touchin.template.activities.StartupActivity"
android:name=".activities.StartupActivity"

2019-05-24 16:37 UTC, BlizzedRu requested changes

2019-05-24 16:37 UTC, BlizzedRu commented on app/src/main/java/ru/touchin/template/di/app/modules/PersistentModule.kt
> +    fun provideSessionStorable(sharedPreferences: SharedPreferences): NonNullStorable<String, String, String> =
А у нас сессия не хранится нигде, кроме как в памяти (в даггере летает) + здесь отсутствует Qualifier для внутреннего параметра SP (или это в дефолтном и будет храниться?)

2019-06-03 11:17 UTC, PilotOfSparrow commented on app/src/main/res/values/styles.xml
> +    <style name="AppTheme" parent="Theme.AppCompat.Light.DarkActionBar">
сразу ```Theme.MaterialComponents.Light.NoActionBar.Bridge``` или что-то вроде того

2019-06-03 13:00 UTC, BlizzedRu approved these changes

2019-06-03 17:47 UTC, merged